version: "3.9"

volumes:
  postgres-data:
  mysql-data:

services:
  blueberry-messaging:
    image: "postgres:15.1"
    volumes:
      - postgres-data:/var/lib/psql-data-blueberry-messaging
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
  lemon-messaging:
    image: "postgres:15.1"
    volumes:
      - postgres-data:/var/lib/psql-data-lemon-messaging
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
  pear-messaging:
    image: "postgres:15.1"
    volumes:
      - postgres-data:/var/lib/psql-data-pear-messaging
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
  blueberry-accounting:
    image: "postgres:15.1"
    volumes:
      - postgres-data:/var/lib/psql-data-blueberry-accounting
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
  lemon-accounting:
    image: "postgres:15.1"
    volumes:
      - postgres-data:/var/lib/psql-data-lemon-accounting
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
  pear-accounting:
    image: "postgres:15.1"
    volumes:
      - postgres-data:/var/lib/psql-data-pear-accounting
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
  blueberry-user-mgmt:
    image: "mysql:8.0.32"
    volumes:
      - mysql-data:/var/lib/mysql-data-blueberry-user-mgmt
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
  lemon-user-mgmt:
    image: "mysql:8.0.32"
    volumes:
      - mysql-data:/var/lib/mysql-data-lemon-user-mgmt
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
  pear-user-mgmt:
    image: "mysql:8.0.32"
    volumes:
      - mysql-data:/var/lib/mysql-data-pear-user-mgmt
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin