name: CI
on:
  push:
    branches:
      - master
      - main
  pull_request:
jobs:
  test_go:
    name: Go tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Test
        run: go test ./... -tags=dev -race -short

  lint_go:
    name: Go lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6

  security_go:
    name: Go dependencies vulnerabilities check
    runs-on: ubuntu-latest
    steps:
      - uses: golang/govulncheck-action@v1
        with:
          go-version-input: '1.24.3'
          go-package: ./...
